// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_frame.proto

#ifndef PROTOBUF_key_5fframe_2eproto__INCLUDED
#define PROTOBUF_key_5fframe_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_key_5fframe_2eproto();
void protobuf_AssignDesc_key_5fframe_2eproto();
void protobuf_ShutdownFile_key_5fframe_2eproto();

class KeyFrame;
class KeyFrameId;

// ===================================================================

class KeyFrameId : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:KeyFrameId) */ {
 public:
  KeyFrameId();
  virtual ~KeyFrameId();

  KeyFrameId(const KeyFrameId& from);

  inline KeyFrameId& operator=(const KeyFrameId& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KeyFrameId& default_instance();

  void Swap(KeyFrameId* other);

  // implements Message ----------------------------------------------

  inline KeyFrameId* New() const { return New(NULL); }

  KeyFrameId* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KeyFrameId& from);
  void MergeFrom(const KeyFrameId& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KeyFrameId* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 trajectory_id = 1;
  void clear_trajectory_id();
  static const int kTrajectoryIdFieldNumber = 1;
  ::google::protobuf::int32 trajectory_id() const;
  void set_trajectory_id(::google::protobuf::int32 value);

  // optional int32 node_index = 2;
  void clear_node_index();
  static const int kNodeIndexFieldNumber = 2;
  ::google::protobuf::int32 node_index() const;
  void set_node_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:KeyFrameId)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 trajectory_id_;
  ::google::protobuf::int32 node_index_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_key_5fframe_2eproto();
  friend void protobuf_AssignDesc_key_5fframe_2eproto();
  friend void protobuf_ShutdownFile_key_5fframe_2eproto();

  void InitAsDefaultInstance();
  static KeyFrameId* default_instance_;
};
// -------------------------------------------------------------------

class KeyFrame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:KeyFrame) */ {
 public:
  KeyFrame();
  virtual ~KeyFrame();

  KeyFrame(const KeyFrame& from);

  inline KeyFrame& operator=(const KeyFrame& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const KeyFrame& default_instance();

  void Swap(KeyFrame* other);

  // implements Message ----------------------------------------------

  inline KeyFrame* New() const { return New(NULL); }

  KeyFrame* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const KeyFrame& from);
  void MergeFrom(const KeyFrame& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(KeyFrame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .KeyFrameId key_frame_id = 1;
  bool has_key_frame_id() const;
  void clear_key_frame_id();
  static const int kKeyFrameIdFieldNumber = 1;
  const ::KeyFrameId& key_frame_id() const;
  ::KeyFrameId* mutable_key_frame_id();
  ::KeyFrameId* release_key_frame_id();
  void set_allocated_key_frame_id(::KeyFrameId* key_frame_id);

  // @@protoc_insertion_point(class_scope:KeyFrame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::KeyFrameId* key_frame_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_key_5fframe_2eproto();
  friend void protobuf_AssignDesc_key_5fframe_2eproto();
  friend void protobuf_ShutdownFile_key_5fframe_2eproto();

  void InitAsDefaultInstance();
  static KeyFrame* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// KeyFrameId

// optional int32 trajectory_id = 1;
inline void KeyFrameId::clear_trajectory_id() {
  trajectory_id_ = 0;
}
inline ::google::protobuf::int32 KeyFrameId::trajectory_id() const {
  // @@protoc_insertion_point(field_get:KeyFrameId.trajectory_id)
  return trajectory_id_;
}
inline void KeyFrameId::set_trajectory_id(::google::protobuf::int32 value) {
  
  trajectory_id_ = value;
  // @@protoc_insertion_point(field_set:KeyFrameId.trajectory_id)
}

// optional int32 node_index = 2;
inline void KeyFrameId::clear_node_index() {
  node_index_ = 0;
}
inline ::google::protobuf::int32 KeyFrameId::node_index() const {
  // @@protoc_insertion_point(field_get:KeyFrameId.node_index)
  return node_index_;
}
inline void KeyFrameId::set_node_index(::google::protobuf::int32 value) {
  
  node_index_ = value;
  // @@protoc_insertion_point(field_set:KeyFrameId.node_index)
}

// -------------------------------------------------------------------

// KeyFrame

// optional .KeyFrameId key_frame_id = 1;
inline bool KeyFrame::has_key_frame_id() const {
  return !_is_default_instance_ && key_frame_id_ != NULL;
}
inline void KeyFrame::clear_key_frame_id() {
  if (GetArenaNoVirtual() == NULL && key_frame_id_ != NULL) delete key_frame_id_;
  key_frame_id_ = NULL;
}
inline const ::KeyFrameId& KeyFrame::key_frame_id() const {
  // @@protoc_insertion_point(field_get:KeyFrame.key_frame_id)
  return key_frame_id_ != NULL ? *key_frame_id_ : *default_instance_->key_frame_id_;
}
inline ::KeyFrameId* KeyFrame::mutable_key_frame_id() {
  
  if (key_frame_id_ == NULL) {
    key_frame_id_ = new ::KeyFrameId;
  }
  // @@protoc_insertion_point(field_mutable:KeyFrame.key_frame_id)
  return key_frame_id_;
}
inline ::KeyFrameId* KeyFrame::release_key_frame_id() {
  // @@protoc_insertion_point(field_release:KeyFrame.key_frame_id)
  
  ::KeyFrameId* temp = key_frame_id_;
  key_frame_id_ = NULL;
  return temp;
}
inline void KeyFrame::set_allocated_key_frame_id(::KeyFrameId* key_frame_id) {
  delete key_frame_id_;
  key_frame_id_ = key_frame_id;
  if (key_frame_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:KeyFrame.key_frame_id)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_key_5fframe_2eproto__INCLUDED
