// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: key_frame.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "key_frame.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* KeyFrameId_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  KeyFrameId_reflection_ = NULL;
const ::google::protobuf::Descriptor* KeyFrame_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  KeyFrame_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_key_5fframe_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_key_5fframe_2eproto() {
  protobuf_AddDesc_key_5fframe_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "key_frame.proto");
  GOOGLE_CHECK(file != NULL);
  KeyFrameId_descriptor_ = file->message_type(0);
  static const int KeyFrameId_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyFrameId, trajectory_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyFrameId, node_index_),
  };
  KeyFrameId_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      KeyFrameId_descriptor_,
      KeyFrameId::default_instance_,
      KeyFrameId_offsets_,
      -1,
      -1,
      -1,
      sizeof(KeyFrameId),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyFrameId, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyFrameId, _is_default_instance_));
  KeyFrame_descriptor_ = file->message_type(1);
  static const int KeyFrame_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyFrame, key_frame_id_),
  };
  KeyFrame_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      KeyFrame_descriptor_,
      KeyFrame::default_instance_,
      KeyFrame_offsets_,
      -1,
      -1,
      -1,
      sizeof(KeyFrame),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyFrame, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KeyFrame, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_key_5fframe_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      KeyFrameId_descriptor_, &KeyFrameId::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      KeyFrame_descriptor_, &KeyFrame::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_key_5fframe_2eproto() {
  delete KeyFrameId::default_instance_;
  delete KeyFrameId_reflection_;
  delete KeyFrame::default_instance_;
  delete KeyFrame_reflection_;
}

void protobuf_AddDesc_key_5fframe_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_key_5fframe_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017key_frame.proto\"7\n\nKeyFrameId\022\025\n\rtraje"
    "ctory_id\030\001 \001(\005\022\022\n\nnode_index\030\002 \001(\005\"-\n\010Ke"
    "yFrame\022!\n\014key_frame_id\030\001 \001(\0132\013.KeyFrameI"
    "db\006proto3", 129);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "key_frame.proto", &protobuf_RegisterTypes);
  KeyFrameId::default_instance_ = new KeyFrameId();
  KeyFrame::default_instance_ = new KeyFrame();
  KeyFrameId::default_instance_->InitAsDefaultInstance();
  KeyFrame::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_key_5fframe_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_key_5fframe_2eproto {
  StaticDescriptorInitializer_key_5fframe_2eproto() {
    protobuf_AddDesc_key_5fframe_2eproto();
  }
} static_descriptor_initializer_key_5fframe_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KeyFrameId::kTrajectoryIdFieldNumber;
const int KeyFrameId::kNodeIndexFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KeyFrameId::KeyFrameId()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:KeyFrameId)
}

void KeyFrameId::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

KeyFrameId::KeyFrameId(const KeyFrameId& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:KeyFrameId)
}

void KeyFrameId::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  trajectory_id_ = 0;
  node_index_ = 0;
}

KeyFrameId::~KeyFrameId() {
  // @@protoc_insertion_point(destructor:KeyFrameId)
  SharedDtor();
}

void KeyFrameId::SharedDtor() {
  if (this != default_instance_) {
  }
}

void KeyFrameId::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* KeyFrameId::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return KeyFrameId_descriptor_;
}

const KeyFrameId& KeyFrameId::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_key_5fframe_2eproto();
  return *default_instance_;
}

KeyFrameId* KeyFrameId::default_instance_ = NULL;

KeyFrameId* KeyFrameId::New(::google::protobuf::Arena* arena) const {
  KeyFrameId* n = new KeyFrameId;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void KeyFrameId::Clear() {
// @@protoc_insertion_point(message_clear_start:KeyFrameId)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(KeyFrameId, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<KeyFrameId*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(trajectory_id_, node_index_);

#undef ZR_HELPER_
#undef ZR_

}

bool KeyFrameId::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KeyFrameId)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 trajectory_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &trajectory_id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_node_index;
        break;
      }

      // optional int32 node_index = 2;
      case 2: {
        if (tag == 16) {
         parse_node_index:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &node_index_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KeyFrameId)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KeyFrameId)
  return false;
#undef DO_
}

void KeyFrameId::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KeyFrameId)
  // optional int32 trajectory_id = 1;
  if (this->trajectory_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->trajectory_id(), output);
  }

  // optional int32 node_index = 2;
  if (this->node_index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->node_index(), output);
  }

  // @@protoc_insertion_point(serialize_end:KeyFrameId)
}

::google::protobuf::uint8* KeyFrameId::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:KeyFrameId)
  // optional int32 trajectory_id = 1;
  if (this->trajectory_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->trajectory_id(), target);
  }

  // optional int32 node_index = 2;
  if (this->node_index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->node_index(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:KeyFrameId)
  return target;
}

int KeyFrameId::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:KeyFrameId)
  int total_size = 0;

  // optional int32 trajectory_id = 1;
  if (this->trajectory_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->trajectory_id());
  }

  // optional int32 node_index = 2;
  if (this->node_index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->node_index());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void KeyFrameId::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KeyFrameId)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const KeyFrameId* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const KeyFrameId>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KeyFrameId)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KeyFrameId)
    MergeFrom(*source);
  }
}

void KeyFrameId::MergeFrom(const KeyFrameId& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KeyFrameId)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.trajectory_id() != 0) {
    set_trajectory_id(from.trajectory_id());
  }
  if (from.node_index() != 0) {
    set_node_index(from.node_index());
  }
}

void KeyFrameId::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KeyFrameId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KeyFrameId::CopyFrom(const KeyFrameId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KeyFrameId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyFrameId::IsInitialized() const {

  return true;
}

void KeyFrameId::Swap(KeyFrameId* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KeyFrameId::InternalSwap(KeyFrameId* other) {
  std::swap(trajectory_id_, other->trajectory_id_);
  std::swap(node_index_, other->node_index_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata KeyFrameId::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = KeyFrameId_descriptor_;
  metadata.reflection = KeyFrameId_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// KeyFrameId

// optional int32 trajectory_id = 1;
void KeyFrameId::clear_trajectory_id() {
  trajectory_id_ = 0;
}
 ::google::protobuf::int32 KeyFrameId::trajectory_id() const {
  // @@protoc_insertion_point(field_get:KeyFrameId.trajectory_id)
  return trajectory_id_;
}
 void KeyFrameId::set_trajectory_id(::google::protobuf::int32 value) {
  
  trajectory_id_ = value;
  // @@protoc_insertion_point(field_set:KeyFrameId.trajectory_id)
}

// optional int32 node_index = 2;
void KeyFrameId::clear_node_index() {
  node_index_ = 0;
}
 ::google::protobuf::int32 KeyFrameId::node_index() const {
  // @@protoc_insertion_point(field_get:KeyFrameId.node_index)
  return node_index_;
}
 void KeyFrameId::set_node_index(::google::protobuf::int32 value) {
  
  node_index_ = value;
  // @@protoc_insertion_point(field_set:KeyFrameId.node_index)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KeyFrame::kKeyFrameIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KeyFrame::KeyFrame()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:KeyFrame)
}

void KeyFrame::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  key_frame_id_ = const_cast< ::KeyFrameId*>(&::KeyFrameId::default_instance());
}

KeyFrame::KeyFrame(const KeyFrame& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:KeyFrame)
}

void KeyFrame::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  key_frame_id_ = NULL;
}

KeyFrame::~KeyFrame() {
  // @@protoc_insertion_point(destructor:KeyFrame)
  SharedDtor();
}

void KeyFrame::SharedDtor() {
  if (this != default_instance_) {
    delete key_frame_id_;
  }
}

void KeyFrame::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* KeyFrame::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return KeyFrame_descriptor_;
}

const KeyFrame& KeyFrame::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_key_5fframe_2eproto();
  return *default_instance_;
}

KeyFrame* KeyFrame::default_instance_ = NULL;

KeyFrame* KeyFrame::New(::google::protobuf::Arena* arena) const {
  KeyFrame* n = new KeyFrame;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void KeyFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:KeyFrame)
  if (GetArenaNoVirtual() == NULL && key_frame_id_ != NULL) delete key_frame_id_;
  key_frame_id_ = NULL;
}

bool KeyFrame::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KeyFrame)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .KeyFrameId key_frame_id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_key_frame_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KeyFrame)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KeyFrame)
  return false;
#undef DO_
}

void KeyFrame::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KeyFrame)
  // optional .KeyFrameId key_frame_id = 1;
  if (this->has_key_frame_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->key_frame_id_, output);
  }

  // @@protoc_insertion_point(serialize_end:KeyFrame)
}

::google::protobuf::uint8* KeyFrame::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:KeyFrame)
  // optional .KeyFrameId key_frame_id = 1;
  if (this->has_key_frame_id()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->key_frame_id_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:KeyFrame)
  return target;
}

int KeyFrame::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:KeyFrame)
  int total_size = 0;

  // optional .KeyFrameId key_frame_id = 1;
  if (this->has_key_frame_id()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->key_frame_id_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void KeyFrame::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KeyFrame)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const KeyFrame* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const KeyFrame>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KeyFrame)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KeyFrame)
    MergeFrom(*source);
  }
}

void KeyFrame::MergeFrom(const KeyFrame& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KeyFrame)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_key_frame_id()) {
    mutable_key_frame_id()->::KeyFrameId::MergeFrom(from.key_frame_id());
  }
}

void KeyFrame::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KeyFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KeyFrame::CopyFrom(const KeyFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KeyFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyFrame::IsInitialized() const {

  return true;
}

void KeyFrame::Swap(KeyFrame* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KeyFrame::InternalSwap(KeyFrame* other) {
  std::swap(key_frame_id_, other->key_frame_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata KeyFrame::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = KeyFrame_descriptor_;
  metadata.reflection = KeyFrame_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// KeyFrame

// optional .KeyFrameId key_frame_id = 1;
bool KeyFrame::has_key_frame_id() const {
  return !_is_default_instance_ && key_frame_id_ != NULL;
}
void KeyFrame::clear_key_frame_id() {
  if (GetArenaNoVirtual() == NULL && key_frame_id_ != NULL) delete key_frame_id_;
  key_frame_id_ = NULL;
}
const ::KeyFrameId& KeyFrame::key_frame_id() const {
  // @@protoc_insertion_point(field_get:KeyFrame.key_frame_id)
  return key_frame_id_ != NULL ? *key_frame_id_ : *default_instance_->key_frame_id_;
}
::KeyFrameId* KeyFrame::mutable_key_frame_id() {
  
  if (key_frame_id_ == NULL) {
    key_frame_id_ = new ::KeyFrameId;
  }
  // @@protoc_insertion_point(field_mutable:KeyFrame.key_frame_id)
  return key_frame_id_;
}
::KeyFrameId* KeyFrame::release_key_frame_id() {
  // @@protoc_insertion_point(field_release:KeyFrame.key_frame_id)
  
  ::KeyFrameId* temp = key_frame_id_;
  key_frame_id_ = NULL;
  return temp;
}
void KeyFrame::set_allocated_key_frame_id(::KeyFrameId* key_frame_id) {
  delete key_frame_id_;
  key_frame_id_ = key_frame_id;
  if (key_frame_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:KeyFrame.key_frame_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
